### PR TITLE
V0.1

### PR DESCRIPTION
**Pull request by jenreiter**

### CODE REVIEW

**Comment by jenreiter** [comment]
@lmperry This PR is ready for review. The gear now has the ability to process filenames with spaces.

**Comment by jenreiter** [comment]
Siemens Dat file: https://storage.cloud.google.com/fw-jen/meas_MID03485_FID51095_siemens.dat?authuser=3&_ga=1.112241100.970475597.1487872009
Optional XML file: https://storage.cloud.google.com/fw-jen/IsmrmrdParameterMap_Siemens.xml?authuser=3&_ga=1.112241100.970475597.1487872009
Optional XSL file: https://storage.cloud.google.com/fw-jen/IsmrmrdParameterMap_Siemens.xsl?authuser=3&_ga=1.150504958.970475597.1487872009

**Review by lmperry — APPROVED** [review]
Looks good. 

- [ ] Can you please add some info and example usage to the README?
- [ ] Also add version of the ISMRMRD code you're using to the label and description in the manifest.

**Comment by jenreiter** [comment]
The requested changes have been made. I will merge this PR, release the version and create a PR to add the gear to the exchange.

**Pull request merged**
